# log4j中定义的级别：fatal(致命错误) > error(错误) >warn(警告) >info(普通信息) >debug(调试信息)>trace(跟踪信息)
#log4j.rootLogger = DEBUG , console表示显示debug及以上等级的信息（即fatal、error、warn、info、debug）
#log4j.rootLogger = DEBUG , console
#只是想看sql执行过程，那么可以整体调高，局部降低
log4j.rootLogger = ERROR , console
# log4j.logger是固定的，a.b是命名空间的名字。
log4j.logger.a.b=TRACE
### console ###
log4j.appender.console = org.apache.log4j.ConsoleAppender
log4j.appender.console.Target = System.out
log4j.appender.console.layout = org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern = [%p] [%-d{yyyy-MM-dd HH\:mm\:ss}] %C.%M(%L) | %m%n